name: "Slither static analysis"
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install Slither and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slither-analyzer
          # Install solc (needed by Slither). Adjust version if your contracts use a different pragma.
          sudo apt-get update
          sudo apt-get install -y solc
      - name: Run slither
        run: |
          # Run slither on contracts/ (adatta il path se i tuoi contratti sono altrove)
          slither contracts/ --json slither-report.json || true
      - name: Upload slither report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.json