name: "Slither static analysis"
on:
  pull_request:
  workflow_dispatch:

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies and solc (native)
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget curl build-essential clang pkg-config python3-dev libssl-dev
          # Add Ethereum PPA and install solc (native compiler). Adjust if you need a specific version.
          sudo add-apt-repository ppa:ethereum/ethereum -y || true
          sudo apt-get update
          sudo apt-get install -y solc || true
          # If the native solc wasn't available from apt, install a specific solc via py-solc-x as fallback
          python3 -m pip install --upgrade pip
          pip3 install py-solc-x
          python3 - <<'PY'
from solcx import get_installed_solc_versions, install_solc
# change the version below to match your contracts' pragma if needed
desired = "0.8.19"
if desired not in [str(v) for v in get_installed_solc_versions()]:
    install_solc(desired)
print("solc versions:", get_installed_solc_versions())
PY

      - name: Install Slither (pip)
        run: |
          python3 -m pip install --upgrade pip
          pip3 install slither-analyzer

      - name: Run slither
        run: |
          # Adatta il path se i tuoi contratti non sono in contracts/
          slither contracts/ --json slither-report.json || true

      - name: Upload slither report
        uses: actions/upload-artifact@v4
        with:
          name: slither-report
          path: slither-report.json